# Generated by Django 3.0.7 on 2020-06-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('1', 'Couple'), ('2', 'Family'), ('3', 'Friends'), ('4', 'Colleagues')], default='1', max_length=2)),
            ],
        ),
    ]
