# Generated by Django 3.0.7 on 2020-06-29 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='group',
            new_name='Groups',
        ),
    ]
